### ISSUE TITLE
FATAL EXCEPTION - Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayerFactory

### ISSUE THREAD

**Issue by Zelfapp** [ened/flutter_plugin_media_info#16]
After `flutter clean` my app now crashes on my screen using `media_info`. I have the `betterplayer` package running and there are no issues with playback. Exoplayer is a dependency in app/build.gradle. So it is there. How can I fix this?

```
D/AndroidRuntime(13655): Shutting down VM
E/AndroidRuntime(13655): FATAL EXCEPTION: main
E/AndroidRuntime(13655): Process: com.myapp.source, PID: 13655
E/AndroidRuntime(13655): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayerFactory;
E/AndroidRuntime(13655): 	at asia.ivity.mediainfo.MediaInfoPlugin.ensureExoPlayer(MediaInfoPlugin.java:365)
E/AndroidRuntime(13655): 	at asia.ivity.mediainfo.MediaInfoPlugin.handleMediaInfoExoPlayer(MediaInfoPlugin.java:176)
E/AndroidRuntime(13655): 	at asia.ivity.mediainfo.MediaInfoPlugin.lambda$handleMediaInfo$0$MediaInfoPlugin(MediaInfoPlugin.java:132)
E/AndroidRuntime(13655): 	at asia.ivity.mediainfo.-$$Lambda$MediaInfoPlugin$FmgGTlALyNlnLFUldbmZd5v5ELM.run(Unknown Source:8)
```

**Comment by ened** [comment]
Should be resolved already.

**Comment by avdisx** [comment]
Plaase using media_info: ^0.9.0.
