### ISSUE TITLE
No virtual method buildOrThrow()

### ISSUE THREAD

**Issue by irjayjay** [ened/flutter_plugin_media_info#33]
Been struggling all day with this, tried various versions, even updated my Flutter version and it persists.

`
E/AndroidRuntime(32392): java.lang.NoSuchMethodError: No virtual method buildOrThrow()Lcom/google/common/collect/ImmutableMap; in class Lcom/google/common/collect/ImmutableMap$Builder; or its super classes (declaration of 'com.google.common.collect.ImmutableMap$Builder' appears in /data/app/~~gWwa4dQnR9W79KhuEUnnGw==/com.whereismytransport.coatl-YdQTYz1izW7Sz3ojEXw4LQ==/base.apk!classes2.dex)
E/AndroidRuntime(32392): 	at com.google.android.exoplayer2.audio.AudioCapabilities.<clinit>(AudioCapabilities.java:75)
E/AndroidRuntime(32392): 	at com.google.android.exoplayer2.audio.DefaultAudioSink$Builder.<init>(DefaultAudioSink.java:267)
E/AndroidRuntime(32392): 	at com.google.android.exoplayer2.DefaultRenderersFactory.buildAudioSink(DefaultRenderersFactory.java:615)
E/AndroidRuntime(32392): 	at com.google.android.exoplayer2.DefaultRenderersFactory.createRenderers(DefaultRenderersFactory.java:294)
E/AndroidRuntime(32392): 	at com.google.android.exoplayer2.ExoPlayerImpl.<init>(ExoPlayerImpl.java:240)
E/AndroidRuntime(32392): 	at com.google.android.exoplayer2.ExoPlayer$Builder.build(ExoPlayer.java:1053)
E/AndroidRuntime(32392): 	at asia.ivity.mediainfo.MediaInfoPlugin.ensureExoPlayer(MediaInfoPlugin.java:398)
E/AndroidRuntime(32392): 	at asia.ivity.mediainfo.MediaInfoPlugin.handleMediaInfoExoPlayer(MediaInfoPlugin.java:186)
E/AndroidRuntime(32392): 	at asia.ivity.mediainfo.MediaInfoPlugin.lambda$handleMediaInfo$0$MediaInfoPlugin(MediaInfoPlugin.java:140)
E/AndroidRuntime(32392): 	at asia.ivity.mediainfo.-$$Lambda$MediaInfoPlugin$uPHi69YmzGsWKYi1mOT1k5DrwGY.run(Unknown Source:8)
E/AndroidRuntime(32392): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(32392): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(32392): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(32392): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(32392): 	at android.app.ActivityThread.main(ActivityThread.java:8669)
E/AndroidRuntime(32392): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32392): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(32392): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
`

**Comment by ened** [comment]
Please submit a small example project via Github that shows this problem.
